-- Foundation Release — local stack environment declaration
--
-- `supabase/seed.sql` refuses to run unless `app.environment` is explicitly
-- `local` or `preview` (MPS-RUL-007, AGENTS.md §11). Nothing set that value on
-- a local `db reset`, so `npm run db:start` and `npm run db:reset` aborted at
-- the seed step with LegacyMigrationSeedError. `supabase/README.md` documents
-- the setting only for a preview project.
--
-- WHY THIS FILE IS SAFE
--
-- It runs from `db.seed.sql_paths`, which the CLI executes ONLY for a local
-- `db reset` / `db start`. `supabase db push` does not run seed files, so this
-- can never execute against the preview or production project — the exact
-- boundary the guard in seed.sql exists to defend. It declares what is already
-- true of this database rather than relaxing the check: seed.sql still refuses
-- to load sample data anywhere the environment has not been declared.
--
-- The CLI batches every seed file onto one connection, so a session-level
-- set_config is visible to seed.sql when it runs next. ALTER DATABASE is not
-- used: the seed role is not a superuser and Postgres refuses it a custom
-- parameter (42501).
select set_config('app.environment', 'local', false);
