import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `supabase start`: a Deno edge-runtime entrypoint the CLI
    // writes into the repo. Git ignores it (supabase/.gitignore) but ESLint did
    // not, so `npm run lint` reported 154 errors in vendor code the moment the
    // local stack had been started once.
    "supabase/.temp/**",
    // Playwright output: traces, error contexts, and copied source.
    "test-results/**",
    "playwright-report/**",
  ]),
])

export default eslintConfig
