import assert from "node:assert/strict"
import { describe, it } from "node:test"

import { DEFAULT_RETURN_TO, safeReturnTo } from "../src/lib/auth/return-to.ts"

/**
 * The return-destination allow-list is the control that stops this application
 * from becoming a phishing redirector: a link to our own sign-in page that
 * lands the visitor on someone else's password form, with our domain in the
 * part of the URL they were taught to check.
 *
 * It is exercised directly rather than only through the browser, because the
 * inputs worth testing are the ones a browser would never send.
 */
describe("safeReturnTo", () => {
  it("keeps a relative same-origin path", () => {
    for (const path of [
      "/family",
      "/educator",
      "/admin",
      "/account",
      "/programs/art-lab",
      "/family?tab=schedule",
      "/family#roster",
    ]) {
      assert.equal(safeReturnTo(path), path)
    }
  })

  it("refuses an absolute URL on another origin", () => {
    for (const hostile of [
      "https://example.com/steal",
      "http://example.com/steal",
      "//example.com/steal",
      "https://home-school-haven.example.com.evil.test/",
    ]) {
      assert.equal(safeReturnTo(hostile), DEFAULT_RETURN_TO)
    }
  })

  it("refuses a backslash, which a browser resolves as a slash", () => {
    /* `/\example.com` reaches a different origin even though it starts with a
       single forward slash — the check that only looks for `//` misses it. */
    for (const hostile of [
      "/\\example.com/steal",
      "/\\/example.com/steal",
      "\\\\example.com/steal",
      "/family\\..\\admin",
    ]) {
      assert.equal(safeReturnTo(hostile), DEFAULT_RETURN_TO)
    }
  })

  it("refuses a control character", () => {
    /* A newline or a null can truncate a header or smuggle a second line into
       one. A destination containing one was not generated by this app. */
    for (const hostile of [
      "/family\nLocation: https://example.com",
      "/family\r\nSet-Cookie: x=1",
      "/family\u0000",
      "/family\u007f",
    ]) {
      assert.equal(safeReturnTo(hostile), DEFAULT_RETURN_TO)
    }
  })

  it("refuses a scheme that is not a path at all", () => {
    for (const hostile of [
      "javascript:alert(1)",
      "data:text/html,<script>alert(1)</script>",
      "mailto:someone@example.com",
      "family",
      "",
    ]) {
      assert.equal(safeReturnTo(hostile), DEFAULT_RETURN_TO)
    }
  })

  it("refuses non-string input", () => {
    /* `formData.get()` returns `File | string | null`, and a search parameter
       can be absent, so this is a real code path rather than a hypothetical. */
    for (const hostile of [null, undefined, 42, {}, ["/family"], true]) {
      assert.equal(safeReturnTo(hostile), DEFAULT_RETURN_TO)
    }
  })

  it("defaults to a route that decides by server-derived role", () => {
    /* `/account` reads `public.user_roles` and routes from there, so a rejected
       destination still lands the viewer somewhere they are authorized to be. */
    assert.equal(DEFAULT_RETURN_TO, "/account")
  })
})
